export const anotherPageTranslations = {
    en: {
        'title': 'Another page',
        'result_dialog_title': 'Result',
        'result_dialog_action_ok': 'ok',
        'first_dialog_title': '1st dialog',
        'first_dialog_content_1': 'first line',
        'first_dialog_content_2': 'second line',
        'first_dialog_action_cancel': 'cancel',
        'first_dialog_action_ok': 'ok',
        'second_dialog_title': '2nd dialog',
        'second_dialog_content_1': 'first line',
        'second_dialog_content_2': 'second line',
        'second_dialog_content_3': 'third line',
        'second_dialog_action_yes': 'yes',
        'second_dialog_action_maybe': 'maybe',
        'second_dialog_action_no': 'no',
        'you_choosed': 'You choosed "{{res}}"',
    },
    ru: {
        'title': 'Другая страница',
        'result_dialog_title': 'Результат',
        'result_dialog_action_ok': 'ок',
        'first_dialog_title': '1й диалог',
        'first_dialog_content_1': 'первая строка',
        'first_dialog_content_2': 'вторая строка',
        'first_dialog_action_cancel': 'отмена',
        'first_dialog_action_ok': 'ок',
        'second_dialog_title': '2й диалог',
        'second_dialog_content_1': 'первая строка',
        'second_dialog_content_2': 'первая строка',
        'second_dialog_content_3': 'третья строка',
        'second_dialog_action_yes': 'да',
        'second_dialog_action_maybe': 'наверно',
        'second_dialog_action_no': 'нет',
        'you_choosed': 'Вы выбрали "{{res}}"',
    }
};
