


function declareDataTypeStringResources(pipTranslateProvider: pip.services.ITranslateProvider) {
    pipTranslateProvider.translations('en', {
        OBJECT_CATEGORY_PERSON: 'Person',
        OBJECT_CATEGORY_EQUIPMENT: 'Equipment',
        OBJECT_CATEGORY_ASSET: 'Asset',

        DEVICE_TYPE_UNKNOWN: 'Undefined',
        DEVICE_TYPE_SIMULATED: 'Simulated',
        DEVICE_TYPE_IOT_TRACKER: 'iot device',
        DEVICE_TYPE_SMART_PHONE: 'Smartphone',
        DEVICE_TYPE_TELTONIKA_FMB: 'Teltonika Fmb',

        ZONE_TYPE_LINE: 'line',
        ZONE_TYPE_POLYGON: 'polygon',
        ZONE_TYPE_CIRCLE: 'circle',
        ZONE_TYPE_OBJECT: 'object',

        OBJECT_TYPE_EMPLOYEE: 'Employee',
        OBJECT_TYPE_CONTRACTOR: 'Contractor',
        OBJECT_TYPE_VISITOR: 'Visitor',
        OBJECT_TYPE_EXCAVATOR: 'Excavator',
        OBJECT_TYPE_HAUL_TRUCK: 'Haul truck',
        OBJECT_TYPE_GRADER: 'Grader',
        OBJECT_TYPE_DRILL: 'Drill',
        OBJECT_TYPE_DOZER: 'Dozer',
        OBJECT_TYPE_BUS: 'Bus',
        OBJECT_TYPE_WATER_TRUCK: 'Water truck',
        OBJECT_TYPE_BLUST_TRUCK: 'Blast truck',
        OBJECT_TYPE_SPECIAL_VEHICLE: 'Special vehicle',
        OBJECT_TYPE_LIGHT_VEHICLE: 'Light vehicle',
        OBJECT_TYPE_PUMP: 'Pump',
        OBJECT_TYPE_GENERATOR: 'Generator',
        OBJECT_TYPE_CRANE: 'Crane',
        OBJECT_TYPE_FORK_LIFT: 'Fork lift',
        OBJECT_TYPE_ACCESS_POINT: 'Access point',
        OBJECT_TYPE_WELDING: 'Welding',
        OBJECT_TYPE_DUMPCAR: 'Dumpcar',
        OBJECT_TYPE_LOCOMOTIVE: 'Locomotive',
        OBJECT_TYPE_VACUUM: 'Vacuum Truck',
        OBJECT_TYPE_OTHER: 'Other',

        SEVERITY_LOW: 'Low',
        SEVERITY_MEDIUM: 'Important',
        SEVERITY_HIGH: 'Critical',

        EVENT_RULE_MEASURE_EMPTY: '',
        EVENT_RULE_MEASURE_TYPE_PRESENCE: 'min',
        EVENT_RULE_MEASURE_TYPE_IMMOBILITY: 'min',
        EVENT_RULE_MEASURE_TYPE_MAX_SPEEDLIMIT: 'km/h',
        EVENT_RULE_MEASURE_TYPE_MIN_SPEEDLIMIT: 'km/h',

        EVENT_RULE_TYPE_SHOWUP: 'Show up',
        EVENT_RULE_TYPE_DISAPPEAR: 'Disappear',
        EVENT_RULE_TYPE_MAX_SPEEDLIMIT: 'Max speed limit',
        EVENT_RULE_TYPE_MIN_SPEEDLIMIT: 'Min speed limit',
        EVENT_RULE_TYPE_ENTRY: 'Entry',
        EVENT_RULE_TYPE_EXIT: 'Exit',
        EVENT_RULE_TYPE_IMMOBILITY: 'Immobility',
        EVENT_RULE_TYPE_PRESENCE: 'Presence',
        // EVENT_RULE_TYPE_BUTTONPRESSED: 'Button pressed',
        // EVENT_RULE_TYPE_BUTTONLONGPRESSED: 'Button long pressed',
        EVENT_RULE_TYPE_BUTTONPRESSED: 'Event 1',
        EVENT_RULE_TYPE_BUTTONLONGPRESSED: 'Event 2',
        EVENT_RULE_TYPE_POWER_OFF: 'Power off',
        EVENT_RULE_TYPE_POWER_ON: 'Power on',

        EVENT_RULE_TYPE_SHOWUP_SHORT: 'Show up',
        EVENT_RULE_TYPE_DISAPPEAR_SHORT: 'Disappear',
        EVENT_RULE_TYPE_MAX_SPEEDLIMIT_SHORT: 'Max',
        EVENT_RULE_TYPE_MIN_SPEEDLIMIT_SHORT: 'Min',
        EVENT_RULE_TYPE_ENTRY_SHORT: 'Entry',
        EVENT_RULE_TYPE_EXIT_SHORT: 'Exit',
        EVENT_RULE_TYPE_IMMOBILITY_SHORT: 'Immobility',
        EVENT_RULE_TYPE_PRESENCE_SHORT: 'Presence',
        // EVENT_RULE_TYPE_BUTTONPRESSED_SHORT: 'Button pressed',
        // EVENT_RULE_TYPE_BUTTONLONGPRESSED_SHORT: 'Button long pressed',
        EVENT_RULE_TYPE_BUTTONPRESSED_SHORT: 'Event 1',
        EVENT_RULE_TYPE_BUTTONLONGPRESSED_SHORT: 'Event 2',
        EVENT_RULE_TYPE_POWER_OFF_SHORT: 'Power off',
        EVENT_RULE_TYPE_POWER_ON_SHORT: 'Power on',

        SIGNAL_TYPE_NONE: 'None',
        SIGNAL_TYPE_ATTENSION: 'Attention',
        SIGNAL_TYPE_CONFIRMATION: 'Confirmation',
        SIGNAL_TYPE_WARNING: 'Warning',
        SIGNAL_TYPE_EMERGENCY: 'Emergency',

        GATEWAY_MODEL_UNKNOWN: 'Unknown',
        GATEWAY_MODEL_MULTI_CONNECT_CONDUIT: 'Multitech Conduit',

        EMERGENCY_ACTION_TYPE_NOTE: 'Note',
        EMERGENCY_ACTION_TYPE_CALL_PHONE: 'Call phone',
        EMERGENCY_ACTION_TYPE_LOCAL_LINK: 'Local link',
        EMERGENCY_ACTION_TYPE_GLOBAL_LINK: 'Global link',

        CORRECTION_PARAMETR_DISTANCE: 'Distance',
        CORRECTION_PARAMETR_ONLINE: 'Online',
        CORRECTION_PARAMETR_OFFLINE: 'Offline',
        CORRECTION_PARAMETR_FREEZED: 'Freezed',
        CORRECTION_PARAMETR_EMERGENCY: 'Emergency',

        CORRECTION_PARAMETR_MEASURE_DISTANCE: 'km.',
        CORRECTION_PARAMETR_MEASURE_ONLINE: 'h.',
        CORRECTION_PARAMETR_MEASURE_OFFLINE: 'h.',
        CORRECTION_PARAMETR_MEASURE_FREEZED: 'min.',
        CORRECTION_PARAMETR_MEASURE_EMERGENCY: 'min.',

        BEACON_TYPE_UNKNOWN: 'Unknown',
        BEACON_TYPE_ALTBEACON: 'AltBeacon',
        BEACON_TYPE_MAX_IBEACON: 'IBeacon',
        BEACON_TYPE_MIN_EDDYSTONEUDI: 'Eddystone-UDI',
        BEACON_TYPE_UNKNOWN_SHORT: 'Unknown',
        BEACON_TYPE_ALTBEACON_SHORT: 'AltBeacon',
        BEACON_TYPE_MAX_IBEACON_SHORT: 'IBeacon',
        BEACON_TYPE_MIN_EDDYSTONEUDI_SHORT: 'Eddystone-UDI',

        INCIDENT_SIGNAL_TYPE_ALL: 'Email and Sms',
        INCIDENT_SIGNAL_TYPE_EMAIL: 'Email',
        INCIDENT_SIGNAL_TYPE_SMS: 'Sms',
        INCIDENT_SIGNAL_TYPE_NONE: 'None',

        GUIDES_INTRODUCTION: 'Introduction',
        GUIDES_RELEASE: 'Release'

    });
    pipTranslateProvider.translations('ru', {
        OBJECT_CATEGORY_PERSON: 'люди',
        OBJECT_CATEGORY_EQUIPMENT: 'машины',
        OBJECT_CATEGORY_ASSET: 'механизмы',

        DEVICE_TYPE_UNKNOWN: 'Не определен',
        DEVICE_TYPE_SIMULATED: 'Симулятор',
        DEVICE_TYPE_IOT_TRACKER: 'IoT трекер',
        DEVICE_TYPE_SMART_PHONE: 'Смартфон',
        DEVICE_TYPE_TELTONIKA_FMB: 'Teltonika Fmb',

        ZONE_TYPE_LINE: 'линия',
        ZONE_TYPE_POLYGON: 'полигон',
        ZONE_TYPE_CIRCLE: 'окружность',
        ZONE_TYPE_OBJECT: 'объект',

        OBJECT_TYPE_EMPLOYEE: 'Сотрудник',
        OBJECT_TYPE_CONTRACTOR: 'Подрядчик',
        OBJECT_TYPE_VISITOR: 'Посетитель',
        OBJECT_TYPE_EXCAVATOR: 'Экскаватор',
        OBJECT_TYPE_HAUL_TRUCK: 'Самосвал',
        OBJECT_TYPE_GRADER: 'Грейдер',
        OBJECT_TYPE_DRILL: 'Бурстанок',
        OBJECT_TYPE_DOZER: 'Бульдозер',
        OBJECT_TYPE_BUS: 'Автобус',
        OBJECT_TYPE_WATER_TRUCK: 'Поливалка',
        OBJECT_TYPE_BLUST_TRUCK: 'Зарядная',
        OBJECT_TYPE_SPECIAL_VEHICLE: 'Специальный автомобиль',
        OBJECT_TYPE_LIGHT_VEHICLE: 'Легковой автомобиль',
        OBJECT_TYPE_PUMP: 'Насос',
        OBJECT_TYPE_GENERATOR: 'Генератор',
        OBJECT_TYPE_CRANE: 'Кран',
        OBJECT_TYPE_FORK_LIFT: 'Подъемник',
        OBJECT_TYPE_ACCESS_POINT: 'Точка доступа',
        OBJECT_TYPE_WELDING: 'Сварочный аппарат',
        OBJECT_TYPE_DUMPCAR: 'Думпкар',
        OBJECT_TYPE_LOCOMOTIVE: 'Тяговый агрегат',
        OBJECT_TYPE_VACUUM: 'Вакуумный Автомобиль',
        OBJECT_TYPE_OTHER: 'Другое',

        SEVERITY_LOW: 'Низкая',
        SEVERITY_MEDIUM: 'Высокая',
        SEVERITY_HIGH: 'Критическая',

        EVENT_RULE_MEASURE_EMPTY: '',
        EVENT_RULE_MEASURE_TYPE_PRESENCE: 'мин',
        EVENT_RULE_MEASURE_TYPE_IMMOBILITY: 'мин',
        EVENT_RULE_MEASURE_TYPE_MAX_SPEEDLIMIT: 'км/ч',
        EVENT_RULE_MEASURE_TYPE_MIN_SPEEDLIMIT: 'км/ч',

        EVENT_RULE_TYPE_SHOWUP: 'Включение трекера',
        EVENT_RULE_TYPE_DISAPPEAR: 'Выключение трекера',
        EVENT_RULE_TYPE_MAX_SPEEDLIMIT: 'Превышение скорости',
        EVENT_RULE_TYPE_MIN_SPEEDLIMIT: 'Ограничение минимальной скорости',
        EVENT_RULE_TYPE_ENTRY: 'Вхождение в зону',
        EVENT_RULE_TYPE_EXIT: 'Выход из зоны',
        EVENT_RULE_TYPE_IMMOBILITY: 'Неподвижность',
        EVENT_RULE_TYPE_PRESENCE: 'Пребывание',
        // EVENT_RULE_TYPE_BUTTONPRESSED: 'Короткое нажатие кнопки',
        // EVENT_RULE_TYPE_BUTTONLONGPRESSED: 'Долгое нажатие кнопки',
        EVENT_RULE_TYPE_BUTTONPRESSED: 'Событие 1',
        EVENT_RULE_TYPE_BUTTONLONGPRESSED: 'Событие 2',
        EVENT_RULE_TYPE_POWER_OFF: 'Выключено питание',
        EVENT_RULE_TYPE_POWER_ON: 'Включено питание',

        EVENT_RULE_TYPE_SHOWUP_SHORT: 'Включение трекера',
        EVENT_RULE_TYPE_DISAPPEAR_SHORT: 'Выключение трекера',
        EVENT_RULE_TYPE_MAX_SPEEDLIMIT_SHORT: 'Макс.',
        EVENT_RULE_TYPE_MIN_SPEEDLIMIT_SHORT: 'Мин.',
        EVENT_RULE_TYPE_ENTRY_SHORT: 'Вхождение в зону',
        EVENT_RULE_TYPE_EXIT_SHORT: 'Выход из зоны',
        EVENT_RULE_TYPE_IMMOBILITY_SHORT: 'Неподвижность',
        EVENT_RULE_TYPE_PRESENCE_SHORT: 'Пребывание',
        EVENT_RULE_TYPE_BUTTONPRESSED_SHORT: 'Событие 1',
        EVENT_RULE_TYPE_BUTTONLONGPRESSED_SHORT: 'Событие 2',
        // EVENT_RULE_TYPE_BUTTONPRESSED_SHORT: 'Короткое нажатие кнопки',
        // EVENT_RULE_TYPE_BUTTONLONGPRESSED_SHORT: 'Долгое нажатие кнопки',
        EVENT_RULE_TYPE_POWER_OFF_SHORT: 'Выключено питание',
        EVENT_RULE_TYPE_POWER_ON_SHORT: 'Включено питание',

        SIGNAL_TYPE_NONE: 'Не задан',
        SIGNAL_TYPE_ATTENSION: 'Внимание',
        SIGNAL_TYPE_CONFIRMATION: 'Подтверждение',
        SIGNAL_TYPE_WARNING: 'Предупреждение',
        SIGNAL_TYPE_EMERGENCY: 'Тревога',

        GATEWAY_MODEL_UNKNOWN: 'Неизвестно',
        GATEWAY_MODEL_MULTI_CONNECT_CONDUIT: 'Multitech Conduit',

        EMERGENCY_ACTION_TYPE_NOTE: 'Текст',
        EMERGENCY_ACTION_TYPE_CALL_PHONE: 'Номер телефона',
        EMERGENCY_ACTION_TYPE_LOCAL_LINK: 'Локальная ссылка',
        EMERGENCY_ACTION_TYPE_GLOBAL_LINK: 'Глобальная ссылка',

        CORRECTION_PARAMETR_DISTANCE: 'Пройденный путь',
        CORRECTION_PARAMETR_ONLINE: 'На связи',
        CORRECTION_PARAMETR_OFFLINE: 'Не на связи',
        CORRECTION_PARAMETR_FREEZED: 'Не подвижный',
        CORRECTION_PARAMETR_EMERGENCY: 'Чрезвычайная ситуация',

        CORRECTION_PARAMETR_MEASURE_DISTANCE: 'км.',
        CORRECTION_PARAMETR_MEASURE_ONLINE: 'ч.',
        CORRECTION_PARAMETR_MEASURE_OFFLINE: 'ч.',
        CORRECTION_PARAMETR_MEASURE_FREEZED: 'мин.',
        CORRECTION_PARAMETR_MEASURE_EMERGENCY: 'мин.',

        BEACON_TYPE_UNKNOWN: 'Unknown',
        BEACON_TYPE_ALTBEACON: 'AltBeacon',
        BEACON_TYPE_MAX_IBEACON: 'IBeacon',
        BEACON_TYPE_MIN_EDDYSTONEUDI: 'Eddystone-UDI',
        BEACON_TYPE_UNKNOWN_SHORT: 'Unknown',
        BEACON_TYPE_ALTBEACON_SHORT: 'AltBeacon',
        BEACON_TYPE_MAX_IBEACON_SHORT: 'IBeacon',
        BEACON_TYPE_MIN_EDDYSTONEUDI_SHORT: 'Eddystone-UDI',

        INCIDENT_SIGNAL_TYPE_ALL: 'Эл. почта и СМС',
        INCIDENT_SIGNAL_TYPE_EMAIL: 'Эл. почта',
        INCIDENT_SIGNAL_TYPE_SMS: 'СМС',
        INCIDENT_SIGNAL_TYPE_NONE: 'Не посылать',

        GUIDES_INTRODUCTION: 'Введение',
        GUIDES_RELEASE: 'Релиз'
    });
}

angular
    .module('iqsTypeCollections.Service')
    .config(declareDataTypeStringResources);
