export const sendSignalDialogTranslateions = {
    en: {
        'SEND_SIGNAL_DIALOG_TITLE': 'Send a signal to trackers',
        'SEND_SIGNAL_TYPE': 'Signal type',
        'SIGNAL_TYPE_NONE': 'None',
        'SIGNAL_TYPE_ATTENTION': 'Attention',
        'SIGNAL_TYPE_CONFIRMATION': 'Confirmation',
        'SIGNAL_TYPE_WARNING': 'Warning',
        'SIGNAL_TYPE_EMERGENCY': 'Emergency',
        'SEND_SIGNAL_OBJECTS': 'Objects',
        'SEND_SIGNAL_ZONES': 'Zones',
        'SEND_SIGNAL_OBJECTS_OR_GROUPS': 'Objects or groups',
        'SEND_SIGNAL_CANCEL': 'Cancel',
        'SEND_SIGNAL_SEND': 'Send',
        'SEND_SIGNAL_SUCCESS': 'Signal sent',
        'SEND_SIGNAL_ERROR_EMPTY': 'There\'s no devices to send signal to.',
        'SEND_SIGNAL_ERROR_UNKNOWN': 'Error happened during sending signal, please try again',
    },
    ru: {
        'SEND_SIGNAL_DIALOG_TITLE': 'Послать сигнал на трекеры',
        'SEND_SIGNAL_TYPE': 'Тип сигнала',
        'SIGNAL_TYPE_NONE': 'Не задан',
        'SIGNAL_TYPE_ATTENTION': 'Внимание',
        'SIGNAL_TYPE_CONFIRMATION': 'Подтверждение',
        'SIGNAL_TYPE_WARNING': 'Предупреждение',
        'SIGNAL_TYPE_EMERGENCY': 'Тревога',
        'SEND_SIGNAL_OBJECTS': 'Объекты',
        'SEND_SIGNAL_ZONES': 'Зоны',
        'SEND_SIGNAL_OBJECTS_OR_GROUPS': 'Объекты или группы',
        'SEND_SIGNAL_CANCEL': 'Отмена',
        'SEND_SIGNAL_SEND': 'Послать',
        'SEND_SIGNAL_SUCCESS': 'Сигнал отправлен',
        'SEND_SIGNAL_ERROR_EMPTY': 'Отсутствуют устройства на которые будет отправлен сигнал.',
        'SEND_SIGNAL_ERROR_UNKNOWN': 'При отправке сигнала произошла ошибка, попробуйте еще раз',
    }
};
