function declareStatisticsFilterStringResources(pipTranslateProvider: pip.services.ITranslateProvider) {
    pipTranslateProvider.translations('en', {
        FILTER_DATE_PERIOD_DAILY: 'For day',
        FILTER_DATE_PERIOD_WEEKLY: 'For week',
        FILTER_DATE_PERIOD_MONTHLY: 'For month',
        FILTER_DATE_PERIOD_YEARLY: 'For year',
        FILTER_DATE_PERIOD_SHIFT: 'For shift',
        FILTER_DATE_PERIOD_RANGE: 'For range',
        FILTER_EVENT_RULE_ALL: 'All events',
        FILTER_OBJECT_ALL: 'All objects',
        FILTER_DEVICES_ALL: 'All devices',
        FILTER_ZONES_ALL: 'All zones',
        FILTER_EVENT_RULE_ACTION_ALL: 'All actions',
        FILTER_PARAMS_ALL: 'Parameter overview',
        FILTER_PARAMS_DISTANCE: 'Distance traveled',
        FILTER_PARAMS_ONLINE: 'Presence',
        FILTER_PARAMS_OFFLINE: 'Time of absence',
        FILTER_PARAMS_FREEZED: 'Freezed',
        FILTER_PARAMS_IMMOBILE: 'Immobility',
        FILTER_PARAMS_SPEED: 'Average speed',
        FILTER_PARAMS_EMERGENCY: 'Emergency',
        FILTER_DIALOG_APPLY: 'Apply',
        STATISTICS_FILTER_DATE_NEXT: 'Next time',
        STATISTICS_FILTER_DATE_CURRENT: 'Current time',
        STATISTICS_FILTER_DATE_PREV: 'Previous time',
        STATISTICS_RANGE_ERROR: 'Date range reach the limit',
        STATISTICS_RANGE_OVERLAP_ERROR: 'End date should be later than begin',
    });
    pipTranslateProvider.translations('ru', {
        FILTER_DATE_PERIOD_DAILY: 'За день',
        FILTER_DATE_PERIOD_WEEKLY: 'За неделю',
        FILTER_DATE_PERIOD_MONTHLY: 'За месяц',
        FILTER_DATE_PERIOD_YEARLY: 'За год',
        FILTER_DATE_PERIOD_SHIFT: 'За смену',
        FILTER_DATE_PERIOD_RANGE: 'За интервал',
        FILTER_EVENT_RULE_ALL: 'Все события',
        FILTER_OBJECT_ALL: 'Все объекты',
        FILTER_DEVICES_ALL: 'Все устройства',
        FILTER_ZONES_ALL: 'Все зоны',
        FILTER_EVENT_RULE_ACTION_ALL: 'Все события',
        FILTER_PARAMS_ALL: 'Обзор параметров',
        FILTER_PARAMS_DISTANCE: 'Пройденное расстояние',
        FILTER_PARAMS_ONLINE: 'Время пребывания',
        FILTER_PARAMS_OFFLINE: 'Время отсутствия',
        FILTER_PARAMS_FREEZED: 'Время полной неподвижности',
        FILTER_PARAMS_IMMOBILE: 'Время неподвижности',
        FILTER_PARAMS_SPEED: 'Средняя скорость',
        FILTER_PARAMS_EMERGENCY: 'Аварийное состояние',
        FILTER_DIALOG_APPLY: 'Применить',
        STATISTICS_FILTER_DATE_NEXT: 'Следующий период',
        STATISTICS_FILTER_DATE_CURRENT: 'Текущий период',
        STATISTICS_FILTER_DATE_PREV: 'Предыдущий период',
        STATISTICS_RANGE_ERROR: 'Длина интервала превысила предельную',
        STATISTICS_RANGE_OVERLAP_ERROR: 'Конечная дата должна быть позже начальной',
    });
}

angular.module('iqsStatisticsFilterPanel')
    .config(declareStatisticsFilterStringResources);