
(() => {

    const translateConfig = function (pipTranslateProvider) {
        pipTranslateProvider.translations('en', {
            SITES_CREATE_TITLE: 'New organization',
            SITES_CREATE_NAME: 'Organization name',
            SITES_CREATE_LOCATION: 'Location',
            SITES_CREATE_TOP: 'Latitude (degrees)',
            SITES_CREATE_LIGHT: 'Longitude (degrees)',
            SITES_CREATE_RADIUS: 'Radius (м)',
            SITES_CREATE_ZONES: 'Timezones',
            SITES_CREATE_TRACKERS_USE_PHONES: 'Use phones',
            SITES_CREATE_TRACKERS_USE_LORA: 'Use lora trackers',
            SITES_CREATE_TRACKERS_USE_LORA_SUBTITLE: 'Using our LoRa tracker devices allows you to monitor your people, vehicles and equipment on the territory of up to 15 kilometers in radius, with the device battery lasting from 20 hours to 8 months, depending on check-in frequency.',
            SITES_CREATE_TRACKERS_INVITE_USERS: 'Invite users',
            SITES_CREATE_PEOPLE_TITLE: 'Invite other management team members',
            SITES_CREATE_PEOPLE_INVITE_USERS: 'Finish',
            SITES_CREATE_CREATE: 'Create organization',
            SITES_CREATE_CANCEL: 'Cancel',
            SITES_CREATE_BACK: 'Back',
            SITES_CREATE_FORVARD: 'Next',
            SITES_CREATE_MAP_DESCRIPTION: 'Position your new workorganization on the map ',
            SITES_CREATE_MAP_DESCRIPTION_LINK: '[how?]',
            ACCOUNT_PHONE_VALIDATE_ERROR: 'Enter a valid phone in e.164 format: +xxxxxxxxxxx',
            ACCOUNT_PHONE_UDI_UNIQUE: 'The entered phone number is already in use',
            ACCOUNT_SERVER_UDI_UNIQUE_ERROR: 'The entered UDI is already in use',
            ACCOUNTT_EMAIL_VALIDATE_ERROR: 'Enter a valid email',
            SITES_CREATE_CREDIT_CARD_TITLE: 'Please, select your payment type.',
            SITES_CREATE_CREDIT_CARD_SUBTITLE1: 'To create your free workorganization, please enter your credit card information',
            SITES_CREATE_CREDIT_CARD_SUBTITLE_LINK: '[why?]',
            SITES_CREATE_CREDIT_CARD_SUBTITLE2: 'For any questions regarding billing and payment, please send us an email at info@iquipsys.com.',
            SITES_CREATE_AGREEMENT_SUBTITLE: 'If you have already signed an agreement with iQuipsys Inc, please enter your company ID and agreement number. For any questions regarding billing, please send us an email at info@iquipsys.com.',
            SITES_CREATE_CREDIT_CARD_HELP_TITLE: 'Why is credit card information required for creating a free organization?',
            SITES_CREATE_CREDIT_CARD_HELP_SUBTITLE: 'The 3-month long trial period is free of charge and allows you to create 1 workorganization and add up to 5 tracker devices. We require credit card information to make sure that you are serious about this trial and truely interested in Positron, as well as to simplify billing if you choose to continue. At any time during your trial period you can disconnect your workorganization and owe nothing. For further information, please see our [Business Proposal](http://www.iquipsys.com/docs/eng/IQuipsys_proposal.pdf).',
            SITES_CREATE_CREDIT_CARD_OPTION_TITLE: 'Credit Card',
            SITES_CREATE_DOGOVOR_OPTION_TITLE: 'Agreement',
            CREDIT_CARD_VISA: 'visa',
            CREDIT_CARD_MAESTRO: 'maestro',
            CREDIT_CARD_MASTERCARD: 'mastercard',
            CREDIT_CARD_DISCOVER: 'discover',
            CREDIT_CARD_AMERICAN_EXPRESS: 'amex',
            SITES_CREATE_CREDIT_CARD_NUMBER_LABEL: 'Credit card number',
            SITES_CREATE_CREDIT_CARD_TYPE_LABEL: 'Card type',
            SITES_CREATE_CREDIT_CARD_NUMBER_PLACEHOLDER: 'Enter card number',
            SITES_CREATE_CREDIT_CARD_FIRST_NAME_LABEL: 'Fisrt Name on Card',
            SITES_CREATE_CREDIT_CARD_LAST_NAME_LABEL: 'Last Name on Card',
            SITES_CREATE_CREDIT_CARD_NAME_PLACEHOLDER: 'Enter the name of the CC holder',
            SITES_CREATE_CREDIT_CARD_CODE_LABEL: 'Security code',
            SITES_CREATE_CREDIT_CARD_CODE_HINT: 'See the oppoorganization side of the card',
            SITE_CONNECTION_FOUND_ERROR: 'You are already connected to this organization',
            SITE_NOT_FOUND_ERROR: 'Organization with such code not found',
            SITE_CREATE_TIP_TITLE: 'Create workorganization.',
            SITE_CREATE_TIP_DESCRIPTION: "Gradually zooming in, find the location of your workorganization. Using the 'pencil' tool, place a dot in the center. Move the cursor away from the center until the circle is big enough to cover all areas of your workorganization. Your trackers will not send any location data when outside of this workorganization area. If you know your organization's exact coordinates, you can enter them below." +
                "\n Your organization's timezone is needed for correct timekeeping.\n You will be able to change these settings later in the system's Configurations section. \n Once logged in, you will be able to create additional workorganizations, if needed.",
            TIPS_CLOSE: 'Close',
            SITES_CREATE_CREDIT_CARD_EXPIRED_LABEL: 'Expires date: month/year',
            SITES_CREATE_AGREEMENT_NUMBER_LABEL: 'Agreement number ',
            SITES_CREATE_AGREEMENT_INN_LABEL: "Company's EIN",
            SITES_CREATE_AGREEMENT_NUMBER_REQ_ERR: 'Enter agreement number',
            SITES_CREATE_AGREEMENT_INN_REQ_ERR: "Enter the company's EIN",
            SITES_CREATE_CREDIT_CARD_NUMBER_REQ_ERR: 'Enter credit card security code',
            SITES_CREATE_CREDIT_CARD_FIRST_NAME_REQ_ERR: "Enter the name of the CC's holder",
            SITES_CREATE_CREDIT_CARD_LAST_NAME_REQ_ERR: "Enter the name of the CC's holder",
            SITES_CREATE_CREDIT_CARD_NUMBER_PATTERN_ERR: 'Incorrect CC number',
            SITES_CREATE_CREDIT_CARD_CODE_REQ_ERR: "Enter your CC's security code (CSC)",
            SITES_CREATE_CREDIT_CARD_FIRST_NAME_PATTERN_ERR: 'Please enter name in English',
            SITES_CREATE_CREDIT_CARD_LAST_NAME_PATTERN_ERR: 'Please enter name in English',
            SITES_CREATE_CREDIT_CARD_CODE_PATTERN_ERR: 'Incorrect security code, please enter 3-4 digit',
            SITES_CREATE_AGREEMENT_VALIDATE_ERROR: 'No such agreement number in our records',

            SITE_CONNECT_NOT_IN_SITE_ROLE_ERROR: 'You do not have access',
            SITE_CONNECT_UNKNOWN_ERROR: 'Unknown error',
            UNKNOWN_ERROR: 'Unknown error',
            SITES_CREATE_CREDIT_CARD_VALIDATION_ERROR: 'Credit card validation error',
            SITES_CREATE_CREDIT_CARD_DUPLICATE_EXTERNAL_CARD_ID: 'Credit cart already exists',
            GLOBAL_SETTINGS_LOCATION_LATTITUDE: 'Latitude (deg)',
            GLOBAL_SETTINGS_LOCATION_LONGITUDE: 'Longitude (deg)',
            GLOBAL_SETTINGS_LOCATION_DISTANSE: 'Radius (km)',
            GLOBAL_SETTINGS_LOCATION_TIMEZONE: 'Timezone',
            ADD_CENTER: 'Add center',
            ZONE_CLEAR_MAP: 'Start over',
            ZONE_ZOOM_IN: 'Zoom in',
            ZONE_ZOOM_OUT: 'Zoom out',
            ZONE_PAN: 'Pan the map',
        });

        pipTranslateProvider.translations('ru', {
            SITES_CREATE_TITLE: 'Новая рабочая площадка',
            SITES_CREATE_NAME: 'Название площадки',
            SITES_CREATE_LOCATION: 'Местоположение новой площадки',
            SITES_CREATE_TOP: 'Широта (град)',
            SITES_CREATE_LIGHT: 'Долгота (град)',
            SITES_CREATE_RADIUS: 'Радиус (м)',
            SITES_CREATE_ZONES: 'Временная зона',
            SITES_CREATE_TRACKERS_USE_PHONES: 'Использовать телефоны',
            SITES_CREATE_TRACKERS_USE_LORA: 'Использовать LoRa трекеры',
            SITES_CREATE_TRACKERS_USE_LORA_SUBTITLE: 'Использование LoRa трекеров позволит вам отслеживать людей, машины и механизмы на территории радиусом до 15 километров, при этом ресурса батарея хватает на время от 20 часов до 8 месяцев, в зависимости от частоты сигнала. Вы можете указать устройства сейчас или после создания прощадки в настройках системы.',
            SITES_CREATE_TRACKERS_INVITE_USERS: 'Пригласить пользователей',
            SITES_CREATE_PEOPLE_TITLE: 'Пригласите членов вашей команды управления',
            SITES_CREATE_PEOPLE_INVITE_USERS: 'Завершить регистрацию',
            SITES_CREATE_CREATE: 'Создать площадку',
            SITES_CREATE_CANCEL: 'Отмена',
            SITES_CREATE_BACK: 'Назад',
            SITES_CREATE_FORVARD: 'Продолжить',
            SITES_CREATE_MAP_DESCRIPTION: 'Выберите местоположение новой площадки ',
            SITES_CREATE_MAP_DESCRIPTION_LINK: '[как?]',
            ACCOUNT_PHONE_VALIDATE_ERROR: 'Используйте E.164 формат для телефонных номеров: +xxxxxxxxxxx',
            ACCOUNT_PHONE_UDI_UNIQUE: 'Введенный номер телефона уже используется',
            ACCOUNT_SERVER_UDI_UNIQUE_ERROR: 'Введенный UDI уже используется',
            ACCOUNTT_EMAIL_VALIDATE_ERROR: 'Введите адрес электронной почты',
            SITES_CREATE_CREDIT_CARD_TITLE: 'Введите способ оплаты и начинайте работу.',
            SITES_CREATE_CREDIT_CARD_SUBTITLE1: 'Для создания бесплатной рабочей площадки, пожалуйста введите информацию о своей кредитной карте ',
            SITES_CREATE_CREDIT_CARD_SUBTITLE_LINK: '[зачем?]',
            SITES_CREATE_CREDIT_CARD_SUBTITLE2: 'По всем вопросам оплаты обращайтесь по адресу: info@iquipsys.com.',
            SITES_CREATE_AGREEMENT_SUBTITLE: 'Если вы заключили с нами договор на обслуживание, введите ИНН вашей компании и номер договора. По всем вопросам оплаты обращайтесь по адресу: info@iquipsys.com.',
            SITES_CREATE_CREDIT_CARD_HELP_TITLE: 'Зачем нам Ваша кредитная карта?',
            SITES_CREATE_CREDIT_CARD_HELP_SUBTITLE: 'Для испытания Позитрона, вы можете создать одну рабочую площадку и добавить первые 5 трекеров на 3 месяца совершенно бесплатно. Информация кредитной карты нужна нам для свидетельства серьезности ваших намерений и для облегчения оплаты в будущем. На протяжении всего времени бесплатного испытания, Вы можете в любой момент удалить вашу площадку и не платить ничего. Полное коммерческое предложение и цены можно посмотреть [здесь](http://www.iquipsys.com/docs/rus/TKP_IQuipsys.pdf).',
            SITES_CREATE_CREDIT_CARD_OPTION_TITLE: 'Кредитная карта',
            SITES_CREATE_DOGOVOR_OPTION_TITLE: 'Договор',
            CREDIT_CARD_VISA: 'visa',
            CREDIT_CARD_MAESTRO: 'maestro',
            CREDIT_CARD_MASTERCARD: 'mastercard',
            CREDIT_CARD_DISCOVER: 'discover',
            CREDIT_CARD_AMERICAN_EXPRESS: 'amex',
            SITES_CREATE_CREDIT_CARD_NUMBER_LABEL: 'Номер карты',
            SITES_CREATE_CREDIT_CARD_TYPE_LABEL: 'Тип карты',
            SITES_CREATE_CREDIT_CARD_NUMBER_PLACEHOLDER: 'Введите номер карты',
            SITES_CREATE_CREDIT_CARD_FIRST_NAME_LABEL: 'Имя на карте',
            SITES_CREATE_CREDIT_CARD_LAST_NAME_LABEL: 'Фамилия на карте',
            SITES_CREATE_CREDIT_CARD_NAME_PLACEHOLDER: 'Введите имя указанное на карте',
            SITES_CREATE_CREDIT_CARD_CODE_LABEL: 'Код безопасности',
            SITES_CREATE_CREDIT_CARD_CODE_HINT: 'Указан на обратной стороне карты',
            SITE_CONNECTION_FOUND_ERROR: 'Вы уже подключены к этой площадке',
            SITE_NOT_FOUND_ERROR: 'Площадка с таким кодом не найдена',
            SITE_CREATE_TIP_TITLE: 'Создание новой площадки.',
            SITE_CREATE_TIP_DESCRIPTION: 'Постепенно приближая область карты, найдите место, где находиться Ваше предприятие. Затем нажмите на кнопку «карандаш» и поставьте на карте точку центра площадки. Потяните в сторону и задайте радиус вашей площадки, так чтобы окружность охватывала все возможные области работы ваших людей и оборудования. Трекеры не будут передавать сигнал за границей вашей рабочей площадки. Если у вас есть точные координаты, вы можете ввести их ниже.' +
                '\n Укажите часовой пояс вашей площадки, для правильного учета времени. \n У Вас будет возможность изменить эти конфигурации в настройках системы. \n Дополнительные площадки также могут быть добавлены позже. ',
            TIPS_CLOSE: 'Закрыть',
            SITES_CREATE_CREDIT_CARD_EXPIRED_LABEL: 'Срок действия: месяц/год',
            SITES_CREATE_AGREEMENT_NUMBER_LABEL: 'Номер договора ',
            SITES_CREATE_AGREEMENT_INN_LABEL: 'ИНН компании',
            SITES_CREATE_AGREEMENT_NUMBER_REQ_ERR: 'Укажите номер договора',
            SITES_CREATE_AGREEMENT_INN_REQ_ERR: 'Укажите ИНН организации',
            SITES_CREATE_CREDIT_CARD_NUMBER_REQ_ERR: 'Укажите код кредитной карты',
            SITES_CREATE_CREDIT_CARD_FIRST_NAME_REQ_ERR: 'Укажите имя владельца кредитной карты',
            SITES_CREATE_CREDIT_CARD_LAST_NAME_REQ_ERR: 'Укажите фамилию владельца кредитной карты',
            SITES_CREATE_CREDIT_CARD_NUMBER_PATTERN_ERR: 'Код кредитной карты введен не верно',
            SITES_CREATE_CREDIT_CARD_CODE_REQ_ERR: 'Укажите код безопасности кредитной карты',
            SITES_CREATE_CREDIT_CARD_FIRST_NAME_PATTERN_ERR: 'Пожалуйста введите имя используя английские символы',
            SITES_CREATE_CREDIT_CARD_LAST_NAME_PATTERN_ERR: 'Пожалуйста введите фамилию используя английские символы',
            SITES_CREATE_CREDIT_CARD_CODE_PATTERN_ERR: 'Неверно введен код безопасности, введите 3 или 4 цифры',
            SITES_CREATE_AGREEMENT_VALIDATE_ERROR: 'Договора с таким номером не существует',

            SITE_CONNECT_NOT_IN_SITE_ROLE_ERROR: 'У Вас нет доступа к сайту',
            SITE_CONNECT_UNKNOWN_ERROR: 'Неизвестная ошибка',
            UNKNOWN_ERROR: 'Неизвестная ошибка',
            SITES_CREATE_CREDIT_CARD_VALIDATION_ERROR: 'Ошибка валидации кредитной карт',
            SITES_CREATE_CREDIT_CARD_DUPLICATE_EXTERNAL_CARD_ID: 'Кредитная карта уже существует',
            GLOBAL_SETTINGS_LOCATION_LATTITUDE: 'Широта (град)',
            GLOBAL_SETTINGS_LOCATION_LONGITUDE: 'Долгота (град)',
            GLOBAL_SETTINGS_LOCATION_DISTANSE: 'Радиус (км)',
            GLOBAL_SETTINGS_LOCATION_TIMEZONE: 'Временная зона',
            ADD_CENTER: 'Добавить центр',
            ZONE_CLEAR_MAP: 'Начать заново',
            ZONE_ZOOM_IN: 'Уменьшить масштаб',
            ZONE_ZOOM_OUT: 'Увеличить масштаб',
            ZONE_PAN: 'Передвинуть карту',
        });
    }

    angular
        .module('iqsNewOrganization')
        .config(translateConfig);

})();

